name: Build app

on:
    push:
        paths:
            - "app/**"

jobs:
    web:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: cd app && yarn add -D typescript && yarn install
