name: Build server

on:
    push:
        paths:
            - "server/**"

jobs:
    server:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: cd server && yarn && yarn build
